# Custom Language File for Launcher Customizer

[ejs.app]
title = "GodCraft Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WELCOME TO GodCraft"
welcomeDescription = ""
welcomeDescCTA = "Copyright Â© 2025 GodCraft"
