# Custom Language File for Launcher Customizer

[ejs.app]
title = "GodCraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.godcraft.it"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.godcraft.it"

[ejs.settings]
sourceGithubLink = "https://discord.godcraft.it"
supportLink = "https://discord.godcraft.it"

[ejs.welcome]
welcomeHeader = "Benvenuto/a su GodCraft"
welcomeDescription = ""
welcomeDescCTA = "Copyright Â© 2025 GodCraft"
